version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - DerekNonGeneric
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: "@typescript-eslint/experimental-utils"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
